#cloud-config

package_upgrade: true
# This assumes Ubuntu 22.04 - most Debian 11 packages are identical, but not all.
packages:
  - curl
  - fail2ban
  - htop
  - net-tools
  - ntp
  - sudo
  - tmux
  - vim
  - wget
  # Backups
  - restic
  # This includes some dev packages for common deployments
  - build-essential
  - libxml2-dev
  - libxslt1-dev
  - libyaml-cpp-dev
  - sqlite3
  - zlib1g-dev
  # Image processing libraries
  - libcairo2-dev
  - libgif-dev 
  - libjpeg-dev
  - libpango1.0-dev
  - librsvg2-dev
  # Other libraries
  - libffi-dev 
  - libldap2-dev
  - libsasl2-dev
  # Piku stack, plus helpers
  - certbot
  - cgroup-tools
  - git
  - nginx-extras
  - python3-click
  - python3-dev
  - python3-pip
  - python3-virtualenv
  - uwsgi
  - uwsgi-plugin-asyncio-python3
  - uwsgi-plugin-gevent-python3
  - uwsgi-plugin-greenlet-python3
  - uwsgi-plugin-python3
  - uwsgi-plugin-tornado-python3
  - uwsgi-plugin-rack-ruby3.0
  # Clojure (will bring in OpenJDK 11)
  # disabled by default to save space
  #- leiningen
  #- uwsgi-plugin-jwsgi-openjdk-11
  - uwsgi-plugin-lua5.1
  - uwsgi-plugin-lua5.2
  - uwsgi-plugin-luajit
  # Optional services (Ubuntu default packages bind these to localhost, be wary of exposed ports if using other distributions)
  # - mongodb-server
  # - mosquitto
  # - postgresql
  # - redis
  
write_files:
  - path: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          root /var/www/html;
          index index.html index.htm;
          server_name _;
          location / {
              try_files $uri $uri/ =404;
          }
      }
      include /home/piku/.piku/nginx/*.conf;

  - path: /etc/uwsgi/apps-enabled/piku.ini
    content: |
      [uwsgi]
      chdir = /home/piku/.piku/uwsgi
      emperor = /home/piku/.piku/uwsgi-enabled
      log-maxsize = 1048576
      logto = /home/piku/.piku/uwsgi/uwsgi.log
      log-backupname = /home/piku/.piku/uwsgi/uwsgi.old.log
      socket = /home/piku/.piku/uwsgi/uwsgi.sock
      uid = piku
      gid = www-data
      enable-threads = true
      threads = 2

  - path: /etc/systemd/system/piku-nginx-watcher.path
    content: |
      [Unit]
      Description=Monitor .piku/nginx for changes

      [Path]
      PathChanged=/home/piku/.piku/nginx
      Unit=piku-nginx-watcher.service

      [Install]
      WantedBy=multi-user.target
  
  - path: /etc/systemd/system/piku-nginx-watcher.service
    content: |
      [Unit]
      Description=Restarts nginx when .piku/nginx changes.

      [Service]
      Type=simple
      ExecStart=/usr/bin/systemctl reload nginx

      [Install]
      WantedBy=multi-user.target

  - path: /etc/ssh/sshd_config
    append: true
    content: |
      Port $SSH_PORT
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

  # If you change the SSH port, don't forget to edit this accordingly
  - path: /etc/fail2ban/jail.d/defaults-debian.conf
    content: |
      [sshd]
      enabled = true
      port = $SSH_PORT

  # Ensure we have inotify working (some of my apps require it)
  - path: /etc/sysctl.conf
    append: true
    content: |
        fs.inotify.max_user_watches=1048576

  # Set up cgroup filesystem so we can limit process RAM and CPU usage
  - path: /etc/systemd/system/cgconfigparser.service
    content: |
        [Unit]
        Description=cgroup config parser
        After=network.target

        [Service]
        User=root
        Group=root
        ExecStart=/usr/sbin/cgconfigparser -L /home/piku/.piku/cgconfig.d
        Type=oneshot

        [Install]
        WantedBy=multi-user.target

  - path: /etc/systemd/system/piku-cgconfigparser-watcher.path
    content: |
      [Unit]
      Description=Monitor .piku/cgconfig.d for changes

      [Path]
      PathChanged=/home/piku/.piku/cgconfig.d
      Unit=piku-cgconfigparser-watcher.service

      [Install]
      WantedBy=multi-user.target
  
  - path: /etc/systemd/system/piku-cgconfigparser-watcher.service
    content: |
      [Unit]
      Description=Restarts cgrulesengd when .piku/cgconfig.d changes.

      [Service]
      Type=simple
      ExecStart=/usr/bin/systemctl restart cgconfigparser

      [Install]
      WantedBy=multi-user.target

  # Set up cgroup allocation rules
  - path: /etc/systemd/system/cgrulesengd.service
    content: |
        [Unit]
        Description=cgroup rules generator
        After=network.target cgconfigparser.service

        [Service]
        User=root
        Group=root
        Type=forking
        EnvironmentFile=-/home/piku/.piku/cgred.conf
        ExecStart=/usr/sbin/cgrulesengd
        Restart=on-failure

        [Install]
        WantedBy=multi-user.target

  - path: /etc/systemd/system/piku-cgrulesengd-watcher.path
    content: |
      [Unit]
      Description=Monitor .piku/cgred.conf for changes

      [Path]
      PathChanged=/home/piku/.piku/cgred.conf
      Unit=piku-cgrulesengd-watcher.service

      [Install]
      WantedBy=multi-user.target
  
  - path: /etc/systemd/system/piku-cgrulesengd-watcher.service
    content: |
      [Unit]
      Description=Restarts cgrulesengd when .piku/cgred.conf changes.

      [Service]
      Type=simple
      ExecStart=/usr/bin/systemctl restart cgrulesengd

      [Install]
      WantedBy=multi-user.target

  # Have the Azure agent set up a swapfile for us
  - path: /etc/waagent.conf
    content: |
        ResourceDisk.Format=y
        ResourceDisk.EnableSwap=y
        ResourceDisk.SwapSizeMB=2048

runcmd:
  # Adjust to taste
  - timedatectl set-timezone Europe/Lisbon
  # Since Azure will provision the admin user first, we can get its public key like this:
  - cat /home/*/.ssh/authorized_keys | head -1 > /tmp/id_rsa.pub
  # Now we can add the Piku user and do the remaining setup
  - adduser --disabled-password --gecos 'PaaS access' --ingroup www-data piku
  - su - piku -c "wget https://raw.githubusercontent.com/piku/piku/master/piku.py && python3 ~/piku.py setup"
  - su - piku -c "python3 ~/piku.py setup:ssh /tmp/id_rsa.pub"
  # Set up cgroup files
  - su - piku -c "mkdir -p ~/.piku/cgconfig.d"
  - su - piku -c "touch ~/.piku/cgred.conf"
  # Remove snaps (primarily useful in smaller VMs)
  - sudo apt-get purge snapd -y
  # Install nodesource LTS version
  - curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
  - apt-get install -y nodejs
  # Basic hygiene in case there are any outstanding dependency changes
  - apt-get update -y
  - apt-get dist-upgrade -y
  - apt-get autoremove -y
  # enable our extra services and give them a chance to generate any error messages in cloud-init logs
  - systemd-analyze verify /etc/systemd/system/piku-*.service
  - systemd-analyze verify /etc/systemd/system/piku-*.path
  - systemctl enable piku-nginx-watcher.path
  - systemctl start piku-nginx-watcher.path
  - systemctl enable piku-cgrulesengd-watcher.path
  - systemctl start piku-cgrulesengd-watcher.path
  - systemctl enable piku-cgconfigparser-watcher.path
  - systemctl start piku-cgconfigparser-watcher.path
  - systemd-analyze verify /etc/systemd/system/cg*.service
  - systemctl enable cgconfigparser
  - systemctl start cgconfigparser
  - systemctl enable cgrulesengd
  - systemctl start cgrulesengd
  # This will clean out /tmp as well
  - reboot
